package entities;
// Generated May 21, 2014 2:37:15 PM by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;

/**
 * TblAdmin generated by hbm2java
 */
public class TblAdmin  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private Byte gender;
     private Date birthday;
     private String email;
     private String phone;
     private Serializable address;
     private Serializable name;
     private byte status;

    public TblAdmin() {
    }

	
    public TblAdmin(int id, String username, String password, String email, byte status) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.email = email;
        this.status = status;
    }
    public TblAdmin(int id, String username, String password, Byte gender, Date birthday, String email, String phone, Serializable address, Serializable name, byte status) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.gender = gender;
       this.birthday = birthday;
       this.email = email;
       this.phone = phone;
       this.address = address;
       this.name = name;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Byte getGender() {
        return this.gender;
    }
    
    public void setGender(Byte gender) {
        this.gender = gender;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Serializable getAddress() {
        return this.address;
    }
    
    public void setAddress(Serializable address) {
        this.address = address;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


